spring:
  port: 8080

cloud.aws:
  region:
    static: us-west-1
    auto: false
  credentials:
    access-key: 
    secret-key: 
    useDefaultAwsCredentialsChain: true
  sqsname: mutant-sqs
  end-point:
    uri: https://sqs.us-west-1.amazonaws.com/374609988338/mutants-sqs
  stack:
    auto: false

mutantdna: ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TCACTG
