spring:
  port: 8080

cloud.aws:
  region:
    static: us-west-1
    auto: false
  credentials:
    access-key: AKIAI56WO4GIZKHOGS6Q
    secret-key: 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
    useDefaultAwsCredentialsChain: true
  sqsname: mutant-sqs
  end-point:
    uri: https://sqs.us-west-1.amazonaws.com/374609988338/mutants-sqs
  stack:
    auto: false

mutantdna: ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TCACTG